# Generated by Django 5.0.4 on 2026-01-18 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banques', '0001_initial'),
        ('releves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapprochementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('periode_annee', models.IntegerField()),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('solde_banque', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solde_interne', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('commentaire', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_rapprochement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements', to='banques.banque')),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements', to='banques.comptebancaire')),
                ('observateur', models.ForeignKey(limit_choices_to={'role': 'AUDITEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements_observes', to=settings.AUTH_USER_MODEL)),
                ('releve_bancaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements', to='releves.relevebancaire')),
            ],
            options={
                'verbose_name': 'Rapprochement Bancaire',
                'verbose_name_plural': 'Rapprochements Bancaires',
                'ordering': ['-periode_annee', '-periode_mois'],
                'unique_together': {('banque', 'compte_bancaire', 'periode_mois', 'periode_annee')},
            },
        ),
    ]
