# Generated by Django 5.0.4 on 2025-11-03 17:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banque', models.CharField(max_length=200, unique=True)),
                ('code_swift', models.CharField(blank=True, help_text='Code SWIFT/BIC', max_length=11, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'ordering': ['nom_banque'],
            },
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_compte', models.CharField(max_length=200)),
                ('numero_compte', models.CharField(max_length=50, unique=True)),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde_courant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_ouverture', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='banques.banque')),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'ordering': ['banque', 'devise', 'intitule_compte'],
                'unique_together': {('banque', 'numero_compte')},
            },
        ),
    ]
