# Generated by Django 4.2.7 on 2026-01-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptebancaire',
            name='date_solde_courant',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière mise à jour du solde courant', null=True, verbose_name='Date de mise à jour du solde courant'),
        ),
    ]
