# Generated by Django 5.0.4 on 2026-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DG', 'Directeur Général'), ('DF', 'Directeur Financier'), ('CD_FINANCE', 'Chef de Division Finance'), ('OPERATEUR_SAISIE', 'Opérateur de Saisie'), ('AGENT_PAYEUR', 'Agent Payeur')], default='OPERATEUR_SAISIE', max_length=20),
        ),
    ]
