# Generated by Django 6.0.2 on 2026-03-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_service_options_service_code_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
    ]
