# Generated by Django 6.0.2 on 2026-04-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_service_options_remove_service_code_service'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rbac_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rbac.role', verbose_name='Rôle RBAC'),
        ),
    ]
