# Generated by Django 6.0.2 on 2026-04-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_rbac_role'),
        ('rbac', '0004_add_rbac_role_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rbac_role_modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_modele', to='rbac.rolemodele', verbose_name='Rôle RBAC (basé sur modèles)'),
        ),
    ]
