# Generated by Django 6.0.2 on 2026-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_rbac_role_modele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DG', 'Directeur Général'), ('DIRECTEUR', 'Directeur'), ('DF', 'Directeur Financier'), ('CD_FINANCE', 'Chef de Division Finance'), ('OPERATEUR_SAISIE', 'Opérateur de Saisie'), ('AGENT_PAYEUR', 'Agent Payeur')], default='OPERATEUR_SAISIE', max_length=20),
        ),
    ]
