# Generated by Django 6.0.2 on 2026-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DG', 'Directeur Général'), ('DIRECTEUR', 'Directeur'), ('DF', 'Directeur Financier'), ('CD_FINANCE', 'Chef de Division Finance'), ('OPERATEUR_SAISIE', 'Opérateur de Saisie'), ('AGENT_PAYEUR', 'Agent Payeur'), ('OpsDaf', 'Opérateur DAF'), ('DirDaf', 'Direction DAF'), ('DivDaf', 'Division DAF'), ('AdminDaf', 'Admin DAF')], default='OPERATEUR_SAISIE', max_length=30),
        ),
    ]
