# Generated by Django 5.0.4 on 2025-11-03 17:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banques', '0001_initial'),
        ('demandes', '0001_initial'),
        ('recettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('releve_pdf', models.FileField(blank=True, null=True, upload_to='releves/pdfs/')),
                ('total_recettes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_depenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solde_banque', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='banques.banque')),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='banques.comptebancaire')),
                ('saisi_par', models.ForeignKey(limit_choices_to={'role': 'OPERATEUR_SAISIE'}, on_delete=django.db.models.deletion.PROTECT, related_name='releves_saisis', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['COMPTABLE', 'DF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé Bancaire',
                'verbose_name_plural': 'Relevés Bancaires',
                'ordering': ['-periode_fin', '-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='MouvementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('reference_operation', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(max_length=3)),
                ('date_operation', models.DateField()),
                ('beneficiaire_ou_source', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lie_a_demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bancaires', to='demandes.demandepaiement')),
                ('lie_a_recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bancaires', to='recettes.recette')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='releves.relevebancaire')),
            ],
            options={
                'verbose_name': 'Mouvement Bancaire',
                'verbose_name_plural': 'Mouvements Bancaires',
                'ordering': ['-date_operation', '-date_creation'],
            },
        ),
    ]
