# Generated by Django 5.0.4 on 2026-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevebancaire',
            name='archive',
            field=models.BooleanField(default=False, help_text='Coché si toutes les dépenses de ce relevé ont été payées', verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
    ]
