# Generated by Django 5.0.4 on 2026-01-18 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('source_recette', models.CharField(choices=[('DROITS_ADMINISTRATIFS', 'Droits administratifs'), ('REDEVANCES', 'Redevances'), ('PARTICIPATIONS', 'Participations'), ('AUTRES', 'Autres')], max_length=30)),
                ('description', models.TextField()),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant USD')),
                ('montant_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant CDF')),
                ('date_encaissement', models.DateField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='recettes/pieces_jointes/')),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='banques.banque')),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='banques.comptebancaire')),
                ('enregistre_par', models.ForeignKey(limit_choices_to={'role__in': ['COMPTABLE', 'OPERATEUR_SAISIE']}, on_delete=django.db.models.deletion.PROTECT, related_name='recettes_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'COMPTABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-date_encaissement', '-date_creation'],
            },
        ),
    ]
