# Generated by Django 5.0.4 on 2026-01-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0001_initial'),
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='banques.banque'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='banques.comptebancaire'),
        ),
    ]
