# Generated by Django 5.0.4 on 2025-11-04 14:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='montant',
        ),
        migrations.AddField(
            model_name='recette',
            name='montant_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant CDF'),
        ),
        migrations.AddField(
            model_name='recette',
            name='montant_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant USD'),
        ),
    ]
