# Generated by Django 5.0.4 on 2026-02-02 15:10

import django.db.models.deletion
from django.db import migrations, models


def create_default_sources(apps, schema_editor):
    """Crée les sources par défaut"""
    SourceRecette = apps.get_model('recettes', 'SourceRecette')
    
    # Créer les sources par défaut
    sources_defaut = [
        ('DROITS_ADMINISTRATIFS', 'Droits administratifs', 'Frais administratifs et droits divers'),
        ('REDEVANCES', 'Redevances', 'Revenus des redevances et royalties'),
        ('PARTICIPATIONS', 'Participations', 'Revenus de participation et dividendes'),
        ('AUTRES', 'Autres', 'Autres sources de revenus non classifiées'),
    ]
    
    for code, nom, description in sources_defaut:
        SourceRecette.objects.get_or_create(
            code=code,
            defaults={'nom': nom, 'description': description}
        )


def migrate_source_data(apps, schema_editor):
    """Migre les données existantes du CharField vers la ForeignKey"""
    SourceRecette = apps.get_model('recettes', 'SourceRecette')
    Recette = apps.get_model('recettes', 'Recette')
    
    # Créer un mapping des codes vers les IDs
    source_map = {}
    for source in SourceRecette.objects.all():
        source_map[source.code] = source.pk
    
    # Mettre à jour les recettes existantes
    for recette in Recette.objects.all():
        if recette.source_recette in source_map:
            recette.new_source_recette_id = source_map[recette.source_recette]
            recette.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_make_banque_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source de recette',
                'verbose_name_plural': 'Sources de recettes',
                'ordering': ['nom'],
            },
        ),
        migrations.RunPython(create_default_sources),
        migrations.AddField(
            model_name='recette',
            name='new_source_recette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recettes_new', to='recettes.sourcerecette'),
        ),
        migrations.RunPython(migrate_source_data),
        migrations.RemoveField(
            model_name='recette',
            name='source_recette',
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='new_source_recette',
            new_name='source_recette',
        ),
    ]
