# Generated by Django 5.0.4 on 2026-02-03 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0002_comptebancaire_date_solde_courant'),
        ('recettes', '0004_sourcerecette_alter_recette_source_recette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='banques.banque'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='banques.comptebancaire'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='source_recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='recettes.sourcerecette'),
        ),
    ]
