# Generated by Django 4.2.7 on 2026-02-06 14:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_alter_recette_banque_alter_recette_compte_bancaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteFeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date', models.DateField(verbose_name='Date')),
                ('libelle_recette', models.CharField(max_length=500, verbose_name='Libellé recette')),
                ('banque', models.CharField(max_length=100, verbose_name='Banque')),
                ('montant_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant FC')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant $us')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recette (feuille)',
                'verbose_name_plural': 'Recettes (feuille)',
                'ordering': ['-date', '-date_creation'],
            },
        ),
    ]
