# Generated by Django 4.2.7 on 2026-02-06 15:18
# Custom migration: preserve banque string data and link to Banque FK

from django.db import migrations, models
import django.db.models.deletion


def populate_banque_fk(apps, schema_editor):
    """Remplit la FK banque à partir du nom (banque_old) en faisant correspondre Banque.nom_banque."""
    RecetteFeuille = apps.get_model('recettes', 'RecetteFeuille')
    Banque = apps.get_model('banques', 'Banque')
    for rec in RecetteFeuille.objects.all():
        if not rec.banque_old or not rec.banque_old.strip():
            continue
        nom = rec.banque_old.strip()
        # Correspondance exacte puis contenant
        banque = Banque.objects.filter(nom_banque__iexact=nom).first()
        if not banque:
            banque = Banque.objects.filter(nom_banque__icontains=nom).first()
        if banque:
            rec.banque = banque
            rec.save(update_fields=['banque_id'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0002_comptebancaire_date_solde_courant'),
        ('recettes', '0006_recette_feuille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recettefeuille',
            old_name='banque',
            new_name='banque_old',
        ),
        migrations.AddField(
            model_name='recettefeuille',
            name='banque',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='recette_feuilles',
                to='banques.banque',
                verbose_name='Banque',
            ),
        ),
        migrations.RunPython(populate_banque_fk, noop),
        migrations.RemoveField(
            model_name='recettefeuille',
            name='banque_old',
        ),
    ]
