# Generated by Django 5.0.4 on 2026-01-27 13:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banques', '0002_comptebancaire_date_solde_courant'),
        ('demandes', '0004_alter_demandepaiement_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etat', models.CharField(choices=[('RELEVE_DEPENSE', 'Relevé de dépenses'), ('DEMANDE_PAIEMENT', 'Demandes de paiement'), ('DEPENSE', 'Dépenses'), ('RECETTE', 'Recettes'), ('PAIEMENT', 'Paiements'), ('Bilan', 'Bilan financier'), ('SOLDE_BANCAIRE', 'Solde bancaire'), ('SITUATION_FINANCIERE', 'Situation financière')], max_length=30, unique=True)),
                ('titre_par_defaut', models.CharField(max_length=200, verbose_name='Titre par défaut')),
                ('description_template', models.TextField(blank=True, verbose_name='Template de description')),
                ('champs_affiches', models.JSONField(default=list, verbose_name='Champs à afficher')),
                ('filtres_disponibles', models.JSONField(default=list, verbose_name='Filtres disponibles')),
                ('template_pdf', models.CharField(default='etats/etat_pdf.html', max_length=100, verbose_name='Template PDF')),
                ('template_excel', models.CharField(blank=True, max_length=100, verbose_name='Template Excel')),
                ('periodicite_defaut', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('PERSONNALISE', 'Personnalisé')], default='MENSUEL', max_length=20)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Configuration d'état",
                'verbose_name_plural': "Configurations d'états",
            },
        ),
        migrations.CreateModel(
            name='EtatGenerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'état")),
                ('type_etat', models.CharField(choices=[('RELEVE_DEPENSE', 'Relevé de dépenses'), ('DEMANDE_PAIEMENT', 'Demandes de paiement'), ('DEPENSE', 'Dépenses'), ('RECETTE', 'Recettes'), ('PAIEMENT', 'Paiements'), ('Bilan', 'Bilan financier'), ('SOLDE_BANCAIRE', 'Solde bancaire'), ('SITUATION_FINANCIERE', 'Situation financière')], max_length=30, verbose_name="Type d'état")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('periodicite', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('PERSONNALISE', 'Personnalisé')], default='PERSONNALISE', max_length=20)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total USD')),
                ('total_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total CDF')),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total général')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='etats/pdfs/', verbose_name='Fichier PDF')),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='etats/excels/', verbose_name='Fichier Excel')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('GENERATION', 'En cours de génération'), ('GENERE', 'Généré'), ('ERREUR', 'Erreur')], default='GENERATION', max_length=20)),
                ('filtres_supplementaires', models.JSONField(blank=True, default=dict, verbose_name='Filtres supplémentaires')),
                ('parametres_affichage', models.JSONField(blank=True, default=dict, verbose_name="Paramètres d'affichage")),
                ('banques', models.ManyToManyField(blank=True, to='banques.banque', verbose_name='Banques')),
                ('comptes_bancaires', models.ManyToManyField(blank=True, to='banques.comptebancaire', verbose_name='Comptes bancaires')),
                ('genere_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etats_generes', to=settings.AUTH_USER_MODEL)),
                ('natures_economiques', models.ManyToManyField(blank=True, to='demandes.natureeconomique', verbose_name='Natures économiques')),
                ('services', models.ManyToManyField(blank=True, to='accounts.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'État généré',
                'verbose_name_plural': 'États générés',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='etats.etatgenerique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de génération',
                'verbose_name_plural': 'Historiques de générations',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='etatgenerique',
            index=models.Index(fields=['type_etat'], name='etats_etatg_type_et_552796_idx'),
        ),
        migrations.AddIndex(
            model_name='etatgenerique',
            index=models.Index(fields=['date_debut', 'date_fin'], name='etats_etatg_date_de_b5e6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='etatgenerique',
            index=models.Index(fields=['statut'], name='etats_etatg_statut_d73c46_idx'),
        ),
        migrations.AddIndex(
            model_name='etatgenerique',
            index=models.Index(fields=['genere_par'], name='etats_etatg_genere__bdf755_idx'),
        ),
    ]
