# Generated by Django 5.0.4 on 2025-11-03 17:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE_DG', 'Validée par le DG'), ('VALIDEE_DF', 'Validée par le DF'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('pieces_justificatives', models.FileField(blank=True, null=True, upload_to='demandes/pieces_justificatives/')),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('service_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='accounts.service')),
            ],
            options={
                'verbose_name': 'Demande de Paiement',
                'verbose_name_plural': 'Demandes de Paiement',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ReleveDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(help_text='Période concernée')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demandes', models.ManyToManyField(related_name='releves_depense', to='demandes.demandepaiement')),
                ('valide_par', models.ForeignKey(limit_choices_to={'role__in': ['DAF', 'DG']}, on_delete=django.db.models.deletion.PROTECT, related_name='releves_depense_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé de Dépense',
                'verbose_name_plural': 'Relevés de Dépense',
                'ordering': ['-periode'],
                'unique_together': {('periode', 'devise')},
            },
        ),
    ]
