# Generated by Django 5.0.4 on 2026-01-18 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='demandes.natureeconomique')),
            ],
            options={
                'verbose_name': 'Nature économique',
                'verbose_name_plural': 'Natures économiques',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NomenclatureDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text="Année d'application de cette nomenclature", verbose_name='Année')),
                ('date_publication', models.DateField(help_text='Date de publication de cette nomenclature', verbose_name='Date de publication')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('DEPASSE', 'Dépassé')], default='EN_COURS', help_text='Statut de la nomenclature (en cours ou dépassé)', max_length=10, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Nomenclature de Dépense',
                'verbose_name_plural': 'Nomenclatures de Dépenses',
                'ordering': ['-annee', '-date_publication'],
                'indexes': [models.Index(fields=['annee'], name='demandes_no_annee_0c8b57_idx'), models.Index(fields=['statut'], name='demandes_no_statut_c4cd56_idx'), models.Index(fields=['date_publication'], name='demandes_no_date_pu_2db64f_idx')],
                'unique_together': {('annee', 'date_publication')},
            },
        ),
        migrations.CreateModel(
            name='DemandePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_deja_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà payé pour cette demande', max_digits=15, verbose_name='Montant déjà payé')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant restant à payer pour cette demande', max_digits=15, verbose_name='Reste à payer')),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('date_demande', models.DateField(blank=True, null=True, verbose_name='Date de demande')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE_DG', 'Validée par le DG'), ('VALIDEE_DF', 'Validée par le DF'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('pieces_justificatives', models.FileField(blank=True, null=True, upload_to='demandes/pieces_justificatives/')),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('service_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='accounts.service')),
                ('nature_economique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='demandes.natureeconomique', verbose_name='Nature économique')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='demandes.nomenclaturedepense', verbose_name='Nomenclature de dépense')),
            ],
            options={
                'verbose_name': 'Demande de Paiement',
                'verbose_name_plural': 'Demandes de Paiement',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ReleveDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Numéro de relevé')),
                ('periode', models.DateField(help_text='Période concernée')),
                ('montant_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant CDF')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant USD')),
                ('ipr_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IPR 3% CDF')),
                ('ipr_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IPR 3% USD')),
                ('net_a_payer_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net à payer CDF')),
                ('net_a_payer_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net à payer USD')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('devise', models.CharField(blank=True, choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], editable=False, max_length=3, null=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('depenses_validees', models.BooleanField(default=False, verbose_name='Dépenses validées')),
                ('date_validation_depenses', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation des dépenses')),
                ('demandes', models.ManyToManyField(related_name='releves_depense', to='demandes.demandepaiement')),
                ('depenses_validees_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['DAF', 'DG', 'COMPTABLE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_depenses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Dépenses validées par')),
                ('valide_par', models.ForeignKey(limit_choices_to={'role__in': ['DAF', 'DG']}, on_delete=django.db.models.deletion.PROTECT, related_name='releves_depense_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé de Dépense',
                'verbose_name_plural': 'Relevés de Dépense',
                'ordering': ['-periode'],
                'unique_together': {('periode',)},
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Numéro de chèque')),
                ('montant_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant CDF')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant USD')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_encaissement', models.DateField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('statut', models.CharField(choices=[('GENERE', 'Généré'), ('EMIS', 'Émis'), ('ENCAISSE', 'Encaissé'), ('ANNULE', 'Annulé')], default='GENERE', max_length=20, verbose_name='Statut')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='banques.banque', verbose_name='Banque')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('releve_depense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='demandes.relevedepense', verbose_name='Relevé de dépense')),
            ],
            options={
                'verbose_name': 'Chèque',
                'verbose_name_plural': 'Chèques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_depense', models.CharField(db_index=True, max_length=50, verbose_name='Code Dépense')),
                ('mois', models.IntegerField(blank=True, null=True, verbose_name='Mois')),
                ('annee', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('date_depense', models.DateField(blank=True, null=True, verbose_name='Date de la dépense')),
                ('date_demande', models.DateField(blank=True, null=True, verbose_name='Date de demande')),
                ('libelle_depenses', models.TextField(verbose_name='Libellé des dépenses')),
                ('montant_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant en CDF')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant en USD')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='depenses/pieces_jointes/', verbose_name='Pièce jointe')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='banques.banque', verbose_name='Banque')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='demandes.nomenclaturedepense', verbose_name='Nomenclature')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-annee', '-mois', 'code_depense'],
                'indexes': [models.Index(fields=['code_depense'], name='demandes_de_code_de_4be6d8_idx'), models.Index(fields=['annee', 'mois'], name='demandes_de_annee_4242eb_idx'), models.Index(fields=['date_depense'], name='demandes_de_date_de_029d12_idx'), models.Index(fields=['banque'], name='demandes_de_banque__3d80f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence du paiement')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('beneficiaire', models.CharField(max_length=50, verbose_name='Beneficiaire')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='demandes.demandepaiement', verbose_name='Demande de paiement')),
                ('paiement_par', models.ForeignKey(limit_choices_to={'role__in': ['COMPTABLE', 'DAF', 'DG']}, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('releve_depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='demandes.relevedepense', verbose_name='Relevé de dépenses')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
                'indexes': [models.Index(fields=['releve_depense'], name='demandes_pa_releve__19ecae_idx'), models.Index(fields=['demande'], name='demandes_pa_demande_e00c4d_idx'), models.Index(fields=['date_paiement'], name='demandes_pa_date_pa_bff639_idx')],
            },
        ),
    ]
