# Generated by Django 5.0.4 on 2025-11-03 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenclatureDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_littera', models.CharField(max_length=20, unique=True, verbose_name='Article Littéra')),
                ('libelle_article', models.CharField(max_length=200, verbose_name='Libellé Article')),
                ('code_compte', models.CharField(max_length=20, verbose_name='Code Compte')),
                ('libelle_compte_principal', models.CharField(max_length=200, verbose_name='Libellé Compte Principal')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nomenclature de Dépense',
                'verbose_name_plural': 'Nomenclatures de Dépenses',
                'ordering': ['article_littera'],
                'indexes': [models.Index(fields=['article_littera'], name='demandes_no_article_a5d09a_idx'), models.Index(fields=['code_compte'], name='demandes_no_code_co_d33d62_idx')],
            },
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='nomenclature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='demandes.nomenclaturedepense', verbose_name='Nomenclature de dépense'),
        ),
    ]
