# Generated by Django 6.0.2 on 2026-04-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depensefeuille',
            name='beneficiaire',
            field=models.CharField(blank=True, help_text='Utilisé en mode workflow pour spécifier le bénéficiaire du paiement', max_length=200, null=True, verbose_name='Bénéficiaire'),
        ),
        migrations.AddField(
            model_name='depensefeuille',
            name='date_paiement',
            field=models.DateTimeField(blank=True, help_text='Utilisé en mode workflow pour enregistrer la date du paiement', null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='depensefeuille',
            name='demande',
            field=models.ForeignKey(blank=True, help_text='Utilisé en mode workflow (Demande → Relevé → Paiement)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depense_feuilles', to='demandes.demandepaiement', verbose_name='Demande de paiement'),
        ),
        migrations.AddField(
            model_name='depensefeuille',
            name='paiement_par',
            field=models.ForeignKey(blank=True, help_text='Utilisé en mode workflow pour identifier qui a effectué le paiement', limit_choices_to={'role__in': ['SUPER_ADMIN', 'ADMIN', 'DG', 'DF', 'CD_FINANCE', 'AGENT_PAYEUR']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depense_feuilles_payees', to=settings.AUTH_USER_MODEL, verbose_name='Payé par'),
        ),
        migrations.AddField(
            model_name='depensefeuille',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Généré automatiquement en mode workflow', max_length=50, null=True, verbose_name='Référence de paiement'),
        ),
        migrations.AddField(
            model_name='depensefeuille',
            name='releve_depense',
            field=models.ForeignKey(blank=True, help_text='Utilisé en mode workflow (Demande → Relevé → Paiement)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depense_feuilles', to='demandes.relevedepense', verbose_name='Relevé de dépenses'),
        ),
    ]
