# Generated by Django 4.2.7 on 2025-11-14 15:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0001_initial'),
        ('demandes', '0002_nomenclaturedepense_demandepaiement_nomenclature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_depense', models.CharField(db_index=True, max_length=50, verbose_name='Code Dépense')),
                ('mois', models.IntegerField(blank=True, null=True, verbose_name='Mois')),
                ('annee', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('date_depense', models.DateField(blank=True, null=True, verbose_name='Date de la dépense')),
                ('article_littera', models.CharField(blank=True, max_length=20, verbose_name='Article Littéra')),
                ('libelle_depenses', models.TextField(verbose_name='Libellé des dépenses')),
                ('montant_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant en CDF')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant en USD')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='banques.banque', verbose_name='Banque')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='demandes.nomenclaturedepense', verbose_name='Nomenclature')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-annee', '-mois', 'code_depense'],
                'indexes': [models.Index(fields=['code_depense'], name='demandes_de_code_de_4be6d8_idx'), models.Index(fields=['annee', 'mois'], name='demandes_de_annee_4242eb_idx'), models.Index(fields=['date_depense'], name='demandes_de_date_de_029d12_idx'), models.Index(fields=['banque'], name='demandes_de_banque__3d80f0_idx')],
            },
        ),
    ]
