# Generated by Django 5.0.4 on 2026-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_remove_unique_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepaiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE_DG', 'Validée par le DG'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
