# Generated by Django 5.0.4 on 2026-02-03 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0002_comptebancaire_date_solde_courant'),
        ('demandes', '0004_alter_demandepaiement_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='banques.banque', verbose_name='Banque'),
        ),
    ]
