# Generated by Django 5.0.4 on 2026-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0005_alter_depense_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureeconomique',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='natureeconomique',
            name='code_parent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code parent'),
        ),
    ]
