# Generated by Django 4.2.7 on 2025-11-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0006_fix_nomenclature_article_littera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclaturedepense',
            options={'ordering': ['-annee', 'article_littera__code'], 'verbose_name': 'Nomenclature de Dépense', 'verbose_name_plural': 'Nomenclatures de Dépenses'},
        ),
        migrations.RemoveIndex(
            model_name='nomenclaturedepense',
            name='demandes_no_article_a5d09a_idx',
        ),
        migrations.RenameIndex(
            model_name='nomenclaturedepense',
            new_name='demandes_no_annee_0c8b57_idx',
            old_name='demandes_no_annee_idx',
        ),
        migrations.RenameIndex(
            model_name='nomenclaturedepense',
            new_name='demandes_no_article_ce351a_idx',
            old_name='demandes_no_art_annee_idx',
        ),
        migrations.AddField(
            model_name='nomenclaturedepense',
            name='date_publication',
            field=models.DateField(blank=True, help_text='Date de publication de cette nomenclature', null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='nomenclaturedepense',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('DEPASSE', 'Dépassé')], default='EN_COURS', help_text='Statut de la nomenclature (en cours ou dépassé)', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='article_littera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='demandes.articlelittera', verbose_name='Article Littéra'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturedepense',
            index=models.Index(fields=['statut'], name='demandes_no_statut_c4cd56_idx'),
        ),
    ]
