# Generated by Django 4.2.7 on 2026-02-06 14:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0006_natureeconomique_active_natureeconomique_code_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseFeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date', models.DateField(verbose_name='Date')),
                ('article_littera', models.CharField(blank=True, max_length=50, verbose_name='Article littéra')),
                ('libelle_depenses', models.CharField(max_length=500, verbose_name='Libellé dépenses')),
                ('banque', models.CharField(max_length=100, verbose_name='Banque')),
                ('montant_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant en Fc')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant en $us')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dépense (feuille)',
                'verbose_name_plural': 'Dépenses (feuille)',
                'ordering': ['-date', '-date_creation'],
            },
        ),
    ]
