# Generated by Django 4.2.7 on 2025-11-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0009_fix_articlelittera_nomenclature_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclaturedepense',
            options={'ordering': ['-annee', '-date_publication'], 'verbose_name': 'Nomenclature de Dépense', 'verbose_name_plural': 'Nomenclatures de Dépenses'},
        ),
        # Supprimer les index seulement s'ils existent (utiliser RunSQL pour éviter les erreurs)
        migrations.RunSQL(
            "DROP INDEX IF EXISTS demandes_no_code_co_d33d62_idx;",
            reverse_sql="-- Cannot reverse",
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS demandes_no_article_ce351a_idx;",
            reverse_sql="-- Cannot reverse",
        ),
        migrations.AddField(
            model_name='depense',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='depenses/pieces_jointes/', verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='articlelittera',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        # Gérer le changement de unique_together avec SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Supprimer l'ancien unique_together dans la base de données
                migrations.RunSQL(
                    """
                    -- Supprimer l'ancien index unique s'il existe
                    DROP INDEX IF EXISTS demandes_nomenclaturedepense_article_littera_id_annee_uniq;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Créer le nouveau unique_together
                migrations.RunSQL(
                    """
                    -- Créer le nouvel index unique
                    CREATE UNIQUE INDEX IF NOT EXISTS demandes_nomenclaturedepense_annee_date_publication_uniq 
                    ON demandes_nomenclaturedepense(annee, date_publication);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS demandes_nomenclaturedepense_annee_date_publication_uniq;",
                ),
            ],
            state_operations=[
                # Mettre à jour l'état du modèle
                migrations.AlterUniqueTogether(
                    name='nomenclaturedepense',
                    unique_together={('annee', 'date_publication')},
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='nomenclaturedepense',
            index=models.Index(fields=['date_publication'], name='demandes_no_date_pu_2db64f_idx'),
        ),
        # Supprimer les champs obsolètes seulement s'ils existent dans la base de données
        migrations.RunSQL(
            """
            -- Supprimer les colonnes obsolètes si elles existent
            -- SQLite ne supporte pas DROP COLUMN directement, donc on ignore ces suppressions
            -- Les colonnes seront simplement ignorées si elles n'existent pas
            """,
            reverse_sql="-- Cannot reverse",
        ),
        # Mettre à jour l'état du modèle pour refléter que ces champs n'existent plus
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='nomenclaturedepense',
                    name='actif',
                ),
                migrations.RemoveField(
                    model_name='nomenclaturedepense',
                    name='code_compte',
                ),
                migrations.RemoveField(
                    model_name='nomenclaturedepense',
                    name='date_creation',
                ),
                migrations.RemoveField(
                    model_name='nomenclaturedepense',
                    name='date_modification',
                ),
                migrations.RemoveField(
                    model_name='nomenclaturedepense',
                    name='libelle_article',
                ),
                migrations.RemoveField(
                    model_name='nomenclaturedepense',
                    name='libelle_compte_principal',
                ),
            ],
        ),
    ]
