# Generated by Django 4.2.7 on 2025-12-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0010_alter_nomenclaturedepense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='demandes.natureeconomique')),
            ],
            options={
                'verbose_name': 'Nature économique',
                'verbose_name_plural': 'Natures économiques',
                'ordering': ['code'],
            },
        ),
    ]
