# Generated by Django 4.2.7 on 2025-12-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0011_natureeconomique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepaiement',
            name='nature_economique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='demandes.natureeconomique', verbose_name='Nature économique'),
        ),
    ]
