# Generated by Django 4.2.7 on 2025-12-02 12:12

from django.db import migrations


def remove_indexes_if_exist(apps, schema_editor):
    """Supprime les index s'ils existent"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Supprimer l'index demandes_no_code_co_d33d62_idx s'il existe
        try:
            cursor.execute("DROP INDEX IF EXISTS demandes_no_code_co_d33d62_idx;")
        except Exception:
            pass
        # Supprimer l'index demandes_no_article_ce351a_idx s'il existe
        try:
            cursor.execute("DROP INDEX IF EXISTS demandes_no_article_ce351a_idx;")
        except Exception:
            pass


def reverse_remove_indexes(apps, schema_editor):
    """Opération inverse (ne fait rien car on ne peut pas recréer les index sans connaître leur structure)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0012_demandepaiement_nature_economique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelittera',
            name='nomenclature',
        ),
        migrations.RunPython(remove_indexes_if_exist, reverse_remove_indexes),
        migrations.RemoveField(
            model_name='depense',
            name='article_littera',
        ),
        migrations.DeleteModel(
            name='ArticleLittera',
        ),
    ]
