# Generated by Django 4.2.7 on 2025-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0013_remove_article_littera'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='date_demande',
            field=models.DateField(blank=True, null=True, verbose_name='Date de demande'),
        ),
    ]
