# Generated by Django 4.2.7 on 2025-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0014_add_date_demande_to_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepaiement',
            name='date_demande',
            field=models.DateField(blank=True, null=True, verbose_name='Date de demande'),
        ),
    ]
