# Generated by Django 4.2.7 on 2025-12-02 17:03

from decimal import Decimal
from django.db import migrations, models


def remove_indexes_if_exist(apps, schema_editor):
    """Supprime les index seulement s'ils existent"""
    db_table = 'demandes_nomenclaturedepense'
    indexes_to_remove = [
        'demandes_no_code_co_d33d62_idx',
        'demandes_no_article_ce351a_idx',
    ]
    
    for index_name in indexes_to_remove:
        try:
            schema_editor.execute(f"DROP INDEX IF EXISTS {index_name}")
        except Exception:
            pass


def reverse_remove_indexes(apps, schema_editor):
    """Fonction inverse (ne fait rien)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0015_add_date_demande_to_demandepaiement'),
    ]

    operations = [
        migrations.RunPython(remove_indexes_if_exist, reverse_remove_indexes),
        migrations.AlterUniqueTogether(
            name='relevedepense',
            unique_together={('periode',)},
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='ipr_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IPR 3% CDF'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='ipr_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IPR 3% USD'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='montant_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant CDF'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='montant_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant USD'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='net_a_payer_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net à payer CDF'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='net_a_payer_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net à payer USD'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='relevedepense',
            name='devise',
            field=models.CharField(blank=True, choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='relevedepense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
    ]
