# Generated by Django 4.2.7 on 2025-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0016_remove_nomenclaturedepense_demandes_no_code_co_d33d62_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevedepense',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Numéro de relevé'),
        ),
    ]
