# Generated by Django 4.2.7 on 2025-12-03 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0017_add_numero_to_relevedepense'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevedepense',
            name='date_validation_depenses',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation des dépenses'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='depenses_validees',
            field=models.BooleanField(default=False, verbose_name='Dépenses validées'),
        ),
        migrations.AddField(
            model_name='relevedepense',
            name='depenses_validees_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['DAF', 'DG', 'COMPTABLE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_depenses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Dépenses validées par'),
        ),
    ]
