# Generated by Django 4.2.7 on 2025-12-05 16:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0018_add_validation_depenses_to_relevedepense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Numéro de chèque')),
                ('montant_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant CDF')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant USD')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_encaissement', models.DateField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('statut', models.CharField(choices=[('GENERE', 'Généré'), ('EMIS', 'Émis'), ('ENCAISSE', 'Encaissé'), ('ANNULE', 'Annulé')], default='GENERE', max_length=20, verbose_name='Statut')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chèque',
                'verbose_name_plural': 'Chèques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='banques.banque', verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='releve_depense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='demandes.relevedepense', verbose_name='Relevé de dépense'),
        ),
    ]
