# Generated by Django 5.0.4 on 2026-01-15 20:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0019_add_cheque_model'),
        ('releves', '0002_relevebancaire_archive_relevebancaire_date_archivage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence du paiement')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('devise', models.CharField(choices=[('USD', 'Dollar US (USD)'), ('CDF', 'Franc Congolais (CDF)')], max_length=3)),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='montant_deja_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà payé pour cette demande', max_digits=15, verbose_name='Montant déjà payé'),
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant restant à payer pour cette demande', max_digits=15, verbose_name='Reste à payer'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='demandes.demandepaiement', verbose_name='Demande de paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='paiement_par',
            field=models.ForeignKey(limit_choices_to={'role__in': ['COMPTABLE', 'DAF', 'DG']}, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='releve_bancaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='releves.relevebancaire', verbose_name='Relevé bancaire'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['releve_bancaire'], name='demandes_pa_releve__ae4b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['demande'], name='demandes_pa_demande_e00c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='demandes_pa_date_pa_bff639_idx'),
        ),
    ]
