# Generated by Django 6.0.2 on 2026-04-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
