# Generated by Django 6.0.2 on 2026-04-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_delete_rolepermission'),
        ('rbac', '0002_rbac_modeles'),
    ]

    operations = [
    ]
