# Generated by Django 6.0.2 on 2026-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_merge_0002_delete_rolepermission_0002_rbac_modeles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodele',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permissionmodele',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolemodele',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rolemodele',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolemodele',
            name='permissions_modeles',
            field=models.ManyToManyField(to='rbac.permissionmodele', verbose_name='Permissions des modèles'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionmodele',
            unique_together={('modele_django', 'action')},
        ),
        migrations.AlterModelTable(
            name='permissionmodele',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rolemodele',
            table=None,
        ),
    ]
