# Generated by Django 6.0.2 on 2026-02-22 22:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=10, verbose_name='Statut')),
                ('solde_ouverture_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name="Solde d'ouverture FC")),
                ('solde_ouverture_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name="Solde d'ouverture USD")),
                ('total_recettes_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total recettes FC')),
                ('total_recettes_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total recettes USD')),
                ('total_depenses_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total dépenses FC')),
                ('total_depenses_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total dépenses USD')),
                ('solde_net_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Solde net FC')),
                ('solde_net_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Solde net USD')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
            ],
            options={
                'verbose_name': 'Clôture mensuelle',
                'verbose_name_plural': 'Clôtures mensuelles',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
